Draft: Account matches support interface
DFE-Digital/support-for-apply-prototype pull request #15
Opened 2021-12-17 17:14 UTC by frankieroberto

Work in progress.

2021-12-20 09:57 UTC, simonwhatley requested changes
I've left some comments and changes inline.

2021-12-20 09:57 UTC, simonwhatley commented on app/routes.js
> +router.get('/candidates/duplicates', (req, res) => {
To keep the same architecture for the support prototype, could you do the following?

In routes.js add the following below the `/candidates` route:

```
router.get('/candidates/dublicates', checkIsAuthenticated, candidateController.duplicate_list_get)
router.get('/candidates/dublicates/:id', checkIsAuthenticated, candidateController.duplicate_show_get)
router.get('/candidates/:id', checkIsAuthenticated, candidateController.show_get)
```

In the candidates' controller, change your `router.get()` to:

```
exports.show_get = (req, res) => {

  res.render('../views/candidates/show', {

  })

}


exports.duplicate_list_get = (req, res) => {

  res.render('../views/candidates/duplicates', {

  })

}

exports.duplicate_show_get = (req, res) => {

  res.render('../views/candidates/duplicate', {

  })

}
```

2021-12-20 09:57 UTC, simonwhatley commented on app/views/candidates/duplicate.njk
> +
```suggestion
{{ govukBackLink({
      text: "Back",
      href: "/candidates/duplicates"
    }) }}
```

2021-12-20 09:57 UTC, simonwhatley commented on app/views/candidates/duplicate.njk
> +    <h1 class="govuk-heading-l">Applications</h1>
```suggestion
    <h1 class="govuk-heading-l">3 candidates with postcode F1 1SD and DOB 01/04/1981</h1>
```

2021-12-20 09:57 UTC, simonwhatley commented on app/views/candidates/duplicate.njk
> +    <h2 class="govuk-heading-m govuk-!-margin-top-3">3 candidates with postcode F1 1SD and DOB 01/04/1981</h2>
```suggestion
  
```

2021-12-20 09:57 UTC, simonwhatley commented on app/views/candidates/duplicate.njk
> +    </table>
Do you have an idea of the extent of the duplication? For example, you show three duplicates here, but could it be many more? If so, it may be better to transpose the data so that candidates are in each row.

2021-12-20 09:57 UTC, simonwhatley commented on app/assets/sass/application.scss
> +  margin-left: 3px;
```suggestion
  @include govuk-font($size: 16, $weight: "bold");
  color: govuk-colour("white");
  display: inline-block;
  min-width: govuk-spacing(3);
  margin-left: govuk-spacing(1);
  padding: 5px 8px 3px 8px;
  border-radius: 75px;
  background-color: $govuk-brand-colour;
  text-align: center;
  white-space: nowrap;
```

2022-01-06 10:11 UTC, frankieroberto commented
@simonwhatley thanks for your comments! This was all done very quickly on the last day before my Christmas break, so there's a fair bit still to do.  I'll probably ask for a re-review when we're closer to done!

2022-01-06 10:13 UTC, frankieroberto commented on app/assets/sass/application.scss
> +  margin-left: 3px;
@simonwhatley can you remember what the intention behind all these suggested changes was? border-radius increased quite a bit?!

2022-01-06 10:14 UTC, frankieroberto commented on app/views/candidates/duplicate.njk
> +    </table>
As I understand it, most of the time there will only be 2 duplicate candidates, but occasionally it might be 3.  It's possible that there'd be even more (which might break the design a bit) but I think that'd be super rare...? @duncanjbrown?

2022-01-06 10:21 UTC, frankieroberto commented on app/routes.js
> +router.get('/candidates/duplicates', (req, res) => {
Thanks, will do this at some point. I was in a hurry so fell back on the pattern I was familiar with... 😄

2022-01-21 12:05 UTC, frankieroberto commented
Closing this, as the design has been iterated upon within the production codebase, and it’s not worth updating this prototype.

2022-01-21 12:05 UTC, closed without merging